services:
  - type: web
    name: nanshe-frontend
    env: node
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm start
    staticPublishPath: build
    routes:
      - src: /.*
        dest: /index.html
